title: TOASTERIA anders-einzigartig-gemütlich
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: einzigartig - gemütlich - anders
color:
  saturation: 0.460914374794811
  brandStrength: 0.25
  rhythmicContrast: 0.2205866605509073
  brandColors:
    - '#4c3632'
    - '#ffffff'
    - '#000000'
    - '#c9c2ad'
    - '#8d7c70'
  lightness: 0.2413668632507324
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Toasteria
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3243728
layout_spectrum: 1
