name: Toasteria
favicon: null
layout_spectrum: 0.41053128358908
typography_spectrum: 0.7532969012390822
title: TOASTERIA anders-einzigartig-gemütlich
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4c3632'
    - '#ffffff'
    - '#000000'
    - '#c9c2ad'
    - '#8d7c70'
  brandStrength: 0.25
  lightness: 0.24136686325073242
  saturation: 0.460914374794811
  rhythmicContrast: 0.22058666055090725
purpose: []
